name: protectic
description: Aplicación de ciberseguridad con IA para adultos mayores

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.8.3

  # Íconos iOS
  cupertino_icons: ^1.0.8

  # Peticiones HTTP
  http: ^1.1.0

  # Reconocimiento de voz
  speech_to_text:

  # Manejo de estados
  provider: ^6.1.2

  # Almacenamiento local
  shared_preferences: ^2.2.2

  # Lanzar enlaces web
  url_launcher: ^6.2.5

  # Indicadores circulares de progreso
  percent_indicator: ^4.2.3

  # Permisos (micrófono, etc.)
  permission_handler: ^11.3.0

  # Firebase (comentado si no se usa aún)
  firebase_core: ^2.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - data/
